[package]
name = "lvgl"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2"
lvgl-sys.path = "../lvgl-sys"
lvgl-base.path = "../lvgl-base"
lvgl-macro.path = "../lvgl-macro"


[features]
sdl2 = []