use rust_lvgl_sys::{
    lv_obj_flag_t_LV_OBJ_FLAG_ADV_HITTEST, lv_obj_flag_t_LV_OBJ_FLAG_CHECKABLE,
    lv_obj_flag_t_LV_OBJ_FLAG_CLICK_FOCUSABLE, lv_obj_flag_t_LV_OBJ_FLAG_CLICKABLE,
    lv_obj_flag_t_LV_OBJ_FLAG_EVENT_BUBBLE, lv_obj_flag_t_LV_OBJ_FLAG_FLOATING,
    lv_obj_flag_t_LV_OBJ_FLAG_GESTURE_BUBBLE, lv_obj_flag_t_LV_OBJ_FLAG_HIDDEN,
    lv_obj_flag_t_LV_OBJ_FLAG_IGNORE_LAYOUT, lv_obj_flag_t_LV_OBJ_FLAG_LAYOUT_1,
    lv_obj_flag_t_LV_OBJ_FLAG_LAYOUT_2, lv_obj_flag_t_LV_OBJ_FLAG_OVERFLOW_VISIBLE,
    lv_obj_flag_t_LV_OBJ_FLAG_PRESS_LOCK, lv_obj_flag_t_LV_OBJ_FLAG_SCROLL_CHAIN,
    lv_obj_flag_t_LV_OBJ_FLAG_SCROLL_CHAIN_HOR, lv_obj_flag_t_LV_OBJ_FLAG_SCROLL_CHAIN_VER,
    lv_obj_flag_t_LV_OBJ_FLAG_SCROLL_ELASTIC, lv_obj_flag_t_LV_OBJ_FLAG_SCROLL_MOMENTUM,
    lv_obj_flag_t_LV_OBJ_FLAG_SCROLL_ON_FOCUS, lv_obj_flag_t_LV_OBJ_FLAG_SCROLL_ONE,
    lv_obj_flag_t_LV_OBJ_FLAG_SCROLL_WITH_ARROW, lv_obj_flag_t_LV_OBJ_FLAG_SCROLLABLE,
    lv_obj_flag_t_LV_OBJ_FLAG_SEND_DRAW_TASK_EVENTS, lv_obj_flag_t_LV_OBJ_FLAG_SNAPPABLE,
    lv_obj_flag_t_LV_OBJ_FLAG_USER_1, lv_obj_flag_t_LV_OBJ_FLAG_USER_2,
    lv_obj_flag_t_LV_OBJ_FLAG_USER_3, lv_obj_flag_t_LV_OBJ_FLAG_USER_4,
    lv_obj_flag_t_LV_OBJ_FLAG_WIDGET_1, lv_obj_flag_t_LV_OBJ_FLAG_WIDGET_2,
};
#[repr(u32)]
pub enum Flag {
    Hidden = lv_obj_flag_t_LV_OBJ_FLAG_HIDDEN,
    Clickable = lv_obj_flag_t_LV_OBJ_FLAG_CLICKABLE,
    ClickFocusable = lv_obj_flag_t_LV_OBJ_FLAG_CLICK_FOCUSABLE,
    Checkable = lv_obj_flag_t_LV_OBJ_FLAG_CHECKABLE,
    Scrollable = lv_obj_flag_t_LV_OBJ_FLAG_SCROLLABLE,
    ScrollElastic = lv_obj_flag_t_LV_OBJ_FLAG_SCROLL_ELASTIC,
    ScrollMomentum = lv_obj_flag_t_LV_OBJ_FLAG_SCROLL_MOMENTUM,
    ScrollOne = lv_obj_flag_t_LV_OBJ_FLAG_SCROLL_ONE,
    ScrollChainHor = lv_obj_flag_t_LV_OBJ_FLAG_SCROLL_CHAIN_HOR,
    ScrollChainVer = lv_obj_flag_t_LV_OBJ_FLAG_SCROLL_CHAIN_VER,
    ScrollChain = lv_obj_flag_t_LV_OBJ_FLAG_SCROLL_CHAIN,
    ScrollOnFocus = lv_obj_flag_t_LV_OBJ_FLAG_SCROLL_ON_FOCUS,
    ScrollWithArrow = lv_obj_flag_t_LV_OBJ_FLAG_SCROLL_WITH_ARROW,
    Snappable = lv_obj_flag_t_LV_OBJ_FLAG_SNAPPABLE,
    PressLock = lv_obj_flag_t_LV_OBJ_FLAG_PRESS_LOCK,
    EventBubble = lv_obj_flag_t_LV_OBJ_FLAG_EVENT_BUBBLE,
    GestureBubble = lv_obj_flag_t_LV_OBJ_FLAG_GESTURE_BUBBLE,
    AdvHittest = lv_obj_flag_t_LV_OBJ_FLAG_ADV_HITTEST,
    IgnoreLayout = lv_obj_flag_t_LV_OBJ_FLAG_IGNORE_LAYOUT,
    Floating = lv_obj_flag_t_LV_OBJ_FLAG_FLOATING,
    SendDrawTaskEvents = lv_obj_flag_t_LV_OBJ_FLAG_SEND_DRAW_TASK_EVENTS,
    OverflowVisible = lv_obj_flag_t_LV_OBJ_FLAG_OVERFLOW_VISIBLE,
    Layout1OrFlexInNewTrack = lv_obj_flag_t_LV_OBJ_FLAG_LAYOUT_1,
    Layout2 = lv_obj_flag_t_LV_OBJ_FLAG_LAYOUT_2,
    Widget1 = lv_obj_flag_t_LV_OBJ_FLAG_WIDGET_1,
    Widget2 = lv_obj_flag_t_LV_OBJ_FLAG_WIDGET_2,
    User1 = lv_obj_flag_t_LV_OBJ_FLAG_USER_1,
    User2 = lv_obj_flag_t_LV_OBJ_FLAG_USER_2,
    User3 = lv_obj_flag_t_LV_OBJ_FLAG_USER_3,
    User4 = lv_obj_flag_t_LV_OBJ_FLAG_USER_4,
}
