use lvgl_sys::{
    lv_align_t_LV_ALIGN_BOTTOM_LEFT, lv_align_t_LV_ALIGN_BOTTOM_MID,
    lv_align_t_LV_ALIGN_BOTTOM_RIGHT, lv_align_t_LV_ALIGN_CENTER, lv_align_t_LV_ALIGN_DEFAULT,
    lv_align_t_LV_ALIGN_LEFT_MID, lv_align_t_LV_ALIGN_OUT_BOTTOM_LEFT,
    lv_align_t_LV_ALIGN_OUT_BOTTOM_MID, lv_align_t_LV_ALIGN_OUT_BOTTOM_RIGHT,
    lv_align_t_LV_ALIGN_OUT_LEFT_BOTTOM, lv_align_t_LV_ALIGN_OUT_LEFT_MID,
    lv_align_t_LV_ALIGN_OUT_LEFT_TOP, lv_align_t_LV_ALIGN_OUT_RIGHT_BOTTOM,
    lv_align_t_LV_ALIGN_OUT_RIGHT_MID, lv_align_t_LV_ALIGN_OUT_RIGHT_TOP,
    lv_align_t_LV_ALIGN_OUT_TOP_LEFT, lv_align_t_LV_ALIGN_OUT_TOP_MID,
    lv_align_t_LV_ALIGN_OUT_TOP_RIGHT, lv_align_t_LV_ALIGN_RIGHT_MID, lv_align_t_LV_ALIGN_TOP_LEFT,
    lv_align_t_LV_ALIGN_TOP_MID, lv_align_t_LV_ALIGN_TOP_RIGHT,
};

#[repr(u8)]
pub enum Align {
    Default = lv_align_t_LV_ALIGN_DEFAULT as _,
    TopLeft = lv_align_t_LV_ALIGN_TOP_LEFT as _,
    TopMid = lv_align_t_LV_ALIGN_TOP_MID as _,
    TopRight = lv_align_t_LV_ALIGN_TOP_RIGHT as _,
    BottomLeft = lv_align_t_LV_ALIGN_BOTTOM_LEFT as _,
    BottomMid = lv_align_t_LV_ALIGN_BOTTOM_MID as _,
    BottomRight = lv_align_t_LV_ALIGN_BOTTOM_RIGHT as _,
    LeftMid = lv_align_t_LV_ALIGN_LEFT_MID as _,
    RightMid = lv_align_t_LV_ALIGN_RIGHT_MID as _,
    Center = lv_align_t_LV_ALIGN_CENTER as _,
    OutTopLeft = lv_align_t_LV_ALIGN_OUT_TOP_LEFT as _,
    OutTopMid = lv_align_t_LV_ALIGN_OUT_TOP_MID as _,
    OutTopRight = lv_align_t_LV_ALIGN_OUT_TOP_RIGHT as _,
    OutBottomLeft = lv_align_t_LV_ALIGN_OUT_BOTTOM_LEFT as _,
    OutBottomMid = lv_align_t_LV_ALIGN_OUT_BOTTOM_MID as _,
    OutBottomRight = lv_align_t_LV_ALIGN_OUT_BOTTOM_RIGHT as _,
    OutLeftTop = lv_align_t_LV_ALIGN_OUT_LEFT_TOP as _,
    OutLeftMid = lv_align_t_LV_ALIGN_OUT_LEFT_MID as _,
    OutLeftBottom = lv_align_t_LV_ALIGN_OUT_LEFT_BOTTOM as _,
    OutRightTop = lv_align_t_LV_ALIGN_OUT_RIGHT_TOP as _,
    OutRightMid = lv_align_t_LV_ALIGN_OUT_RIGHT_MID as _,
    OutRightBottom = lv_align_t_LV_ALIGN_OUT_RIGHT_BOTTOM as _,
}
