[package]
name = "rust-lvgl-sys"
version = "0.1.0"
edition = "2024"

[dependencies]

[features]
sdl2 = []
tiny_ttf = []
tiny_ttf_file = ["tiny_ttf"]
qrcode = []
pinyin = []
lottie = []
gif = []

[build-dependencies]
cc = "1.2.30"
bindgen = "0.72.0"
